import '../styles/globals.css';
import Head from 'next/head';
import { PHProvider } from './providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Cinzel&family=Cinzel+Decorative&display=swap"
        />
      </Head>
      <body>
        <PHProvider>{children}</PHProvider>
      </body>
    </html>
  );
}
